name: Multi-Job Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Running Job 1"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Step 2
        run: |
          echo "Running Job 2"
          exit 1  # Simulate failure

  job3:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Step 3
        run: |
          echo "Running Job 3"
          exit 1  # Simulate failure

  job4:
    needs: [job2, job3]
    if: always()  # Ensure Job4 always runs, even if Job2 and Job3 fail
    runs-on: ubuntu-latest
    steps:
      - name: Check if Job2 and Job3 both failed
        run: |
          if [[ "${{ needs.job2.result }}" == "failure" && "${{ needs.job3.result }}" == "failure" ]]; then
            echo "Both Job2 and Job3 failed. Failing Job4 to prevent merge."
            exit 1
          fi
          
      - name: Run Job4
        run: echo "Running Job 4"
