name: Multi-Job Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Running Job 1"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Step 2
        run: |
          echo "Running Job 2"
          exit 1  # Simulating failure

  job3:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Step 3
        run: |
          echo "Running Job 3"
          exit 1  # Simulating failure

  job4:
    needs: [job2, job3]
    if: ${{ needs.job2.result == 'success' || needs.job3.result == 'success' }}  # Run only if at least one passes
    runs-on: ubuntu-latest
    steps:
      - name: Step 4
        run: echo "Running Job 4"
